name: Container Images

on:
  push:
    branches: [ "develop", "main" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write


env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAGS: latest ${{ github.ref_name }} ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update
        sudo apt-get -y install qemu-user-static
    - id: build_image
      name: Build Image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        platforms: linux/amd64, linux/arm64
        tags: ${{ env.IMAGE_TAGS }}
        containerfiles: |
          ./Containerfile
    - id: push_image
      if: github.ref_type == 'tag'
      name: Push Image to GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}
